---
- name: deploy infrastructure configuration
  hosts: ios

  tasks:
    - name: configure infrastructure interfaces
      ios_template:
        src: "{{ playbook_dir }}/infra/{{ inventory_hostname }}.cfg"
        provider: "{{ cli }}"

