---
- name: enable nxapi on cisco nxos hosts
  hosts: nxos

  tasks:
    - name: configure nxapi support
      nxos_config:
        lines:
          - feature nxapi
        provider: "{{ cli }}"

    - name: verify nxapi status
      nxos_command:
        commands: show nxapi | json
        waitfor: result[0].http_port eq 80
        provider: "{{ cli }}"

