---
- name: backup running-config from vyos device
  vyos_command:
    commands: show configuration
    provider: "{{ provider }}"
  register: config

- name: set backup_file fact
  set_fact:
    backup_file: "{{ backup_path }}/{{ inventory_hostname }}/running-config"

- name: write backup to file
  copy:
    content: "{{ config.stdout[0] }}"
    dest: "{{ backup_file }}"

- name: display backup_file path
  debug: var=backup_file
