- name: collect device facts
  setup:
  delegate_to: "{{ inventory_hostname }}"
  connection: smart

- name: set hostname fact
  set_fact: hostname="{{ ansible_hostname }}"

- name: set version fact
  set_fact: version="{{ ansible_lsb.release }}"
