---
- name: collect output from eos device
  eos_command:
    commands:
      - show version | json
      - show hostname | json
      - show interfaces
      - show running-config all
    provider: "{{ cli }}"
  register: output
  connection: local

# common facts
#

- name: set hostname fact
  set_fact: hostname="{{ output.stdout[1].hostname }}"

- name: set interfaces fact
  set_fact: interfaces="{{ output.stdout[2] | regex_findall('^([E|L|M|P|V]\\S+)') }}"

- name: set version fact
  set_fact: version="{{ output.stdout[0].version }}"

- name: set config fact
  set_fact: config="{{ output.stdout[3] }}"

- name: set config_lines fact
  set_fact: config_lines="{{ config.split('\n') }}"



