---
- name: collect output from nxos device
  nxos_command:
    commands:
      - show version | json
      - show interface
      - show running-config all
    provider: "{{ cli }}"
  register: output

# common facts
#

- name: set hostname fact
  set_fact: hostname="{{ output.stdout[0].host_name }}"

- name: set interfaces fact
  set_fact: interfaces="{{ output.stdout[1] | regex_findall('^([E|L|P|V]\\S+)') }}"

- name: set version fact
  set_fact: version="{{ output.stdout[0].sys_ver_str }}"

- name: set config fact
  set_fact: config="{{ output.stdout[2] }}"

- name: set config_lines fact
  set_fact: config_lines="{{ config.split('\n') }}"


